use_frameworks!

platform :ios, '8.0'

target 'QinTestSDK_Example' do
  pod 'QinTestSDK', :path => '../'

  target 'QinTestSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
